### ISSUE TITLE
gps_get_date() actually calls gps_get_time()

### ISSUE THREAD

**Issue by srl295** [tessel/t1-firmware#141]
https://github.com/tessel/t1-firmware/blob/master/src/hw/l_hw.c#L735

Shouldn't this be `gps_get_date()`? Looks like a copy and paste error.
```
> var hw = process.binding('hw'); [ hw.gps_get_time(), hw.gps_get_date() ]
[ 213053.119, 213053.119 ]
```

Related: https://github.com/tessel/gps-a2235h/issues/3

**Comment by srl295** [comment]
btw the above fix did seem to work for me, except that somehow the time and datestamps became integer (no fractional seconds).

**Comment by johnnyman727** [comment]
@srl295 thanks for catching this! Do you think you'll be able to open a PR and roll that change in?

**Comment by srl295** [comment]
@johnnyman727 yes i will open a PR!

**Comment by yetzt** [comment]
after merging the fix, when will there be a new firmware to update my tessel?

**Comment by johnnyman727** [comment]
@yetzt I will try to put out a new release this week. As you may have noticed, nobody else is actively working on T1 so the process of putting out a new build is a bit of a forgotten art. I also want to change one API that is incompatible with T2 so we may be able to kill two birds with one stone.

**Comment by yetzt** [comment]
@johnnyman727 i noticed. thanks for caring! <3

**Comment by johnnyman727** [comment]
@yetzt new build should be available now (`0.2.0`)

**Comment by yetzt** [comment]
\o/ <3 thanks @johnnyman727

**Comment by srl295** [comment]
Ooh- thanks!
